// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz0_JBotEJCwN72olxVOReOnZAq7KRUxE',
    appId: '1:671274223620:web:ef1a0b2a49e8ccc7380d51',
    messagingSenderId: '671274223620',
    projectId: 'shotspot-12b2c',
    authDomain: 'shotspot-12b2c.firebaseapp.com',
    storageBucket: 'shotspot-12b2c.firebasestorage.app',
    measurementId: 'G-B4D0ZVR7KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8uyA4Eyb4C90bIsI2Fs2DYB1DAmC_JuM',
    appId: '1:671274223620:android:21d54fc5b8aeb673380d51',
    messagingSenderId: '671274223620',
    projectId: 'shotspot-12b2c',
    storageBucket: 'shotspot-12b2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2b_cndq8WPCG5HLq_pgisja9hbojGPJ0',
    appId: '1:671274223620:ios:6bbec4906b999e41380d51',
    messagingSenderId: '671274223620',
    projectId: 'shotspot-12b2c',
    storageBucket: 'shotspot-12b2c.firebasestorage.app',
    iosBundleId: 'com.example.shotSpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2b_cndq8WPCG5HLq_pgisja9hbojGPJ0',
    appId: '1:671274223620:ios:6bbec4906b999e41380d51',
    messagingSenderId: '671274223620',
    projectId: 'shotspot-12b2c',
    storageBucket: 'shotspot-12b2c.firebasestorage.app',
    iosBundleId: 'com.example.shotSpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz0_JBotEJCwN72olxVOReOnZAq7KRUxE',
    appId: '1:671274223620:web:b795a20d255b8ef8380d51',
    messagingSenderId: '671274223620',
    projectId: 'shotspot-12b2c',
    authDomain: 'shotspot-12b2c.firebaseapp.com',
    storageBucket: 'shotspot-12b2c.firebasestorage.app',
    measurementId: 'G-YY7JWXTDPQ',
  );
}
